I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 189, in script
    python:
  File "renpy/common/00start.rpy", line 190, in <module>
    renpy.execute_default_statement(True)
Exception: store.complete_hallway is being given a default a second time.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 189, in script
    python:
  File "D:\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 190, in <module>
    renpy.execute_default_statement(True)
  File "D:\renpy-8.1.3-sdk\renpy\exports.py", line 3982, in execute_default_statement
    i.execute_default(start)
  File "game/var.rpyc", line 1, in execute_default
Exception: store.complete_hallway is being given a default a second time.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
gorelov_home 1.0
Sat Nov 11 20:46:11 2023
